## 

ARG GIT_HASH
ARG VERSION
ARG RELEASE_DATE
ARG UPSTREAM_IMAGE

FROM ${UPSTREAM_IMAGE}

# COPY localfiles /usr/src/mycontainer
# EXPOST 9999

# CMD [ "--my", "--custom", "--params" ]

LABEL maintainer="Steve Miller <me@r15cookie.com>"
LABEL version="${VERSION}"
LABEL git_hash="${GIT_HASH}"
LABEL release-date="${RELEASE_DATE}"