inage: quay.io/ssmiller25/gitpod-k8s:20211121-2
#image:
#  file: .gitpod.Dockerfile

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - ms-kubernetes-tools.vscode-kubernetes-tools

tasks:
  - name: Civo Env
    command: sh ./scripts/gitpod/gitpod-civo-env.sh
