apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server
spec:
  template:
    spec:
      initContainers:
        - name: addons
          image: quay.io/ssmiller25/k8s-code-server:3.12.0-1
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVICE_URL
              value: https://open-vsx.org/vscode/gallery
            - name: ITEM_URL
              value: https://open-vsx.org/vscode/item
          command:
            - sh
            - -c
            - |
              code-server --install-extension ms-python.python
              code-server --install-extension golang.Go
          volumeMounts:
            - name: data
              mountPath: /home/coder