---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-red
  namespace: homeassistant
  labels:
    app: node-red
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-red
  template:
    metadata:
      labels:
        app: node-red
    spec:
      containers:
      - name: node-red
        image: nodered/node-red:latest
        ports:
        - containerPort: 1880
          name: node-red-ui
        securityContext:
          privileged: true
        volumeMounts:
        - name: node-red-data
          mountPath: /data
        env:
        - name: TZ
          value: America/Chicago
      volumes:
      - name: node-red-data
        persistentVolumeClaim:
          claimName: node-red
---
apiVersion: v1
kind: Service
metadata:
  name: node-red
spec:
  selector:
    app: node-red
  type: ClusterIP
  ports:
    - name: node-red-ui
      port: 1880
      protocol: TCP
      targetPort: node-red-ui
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-red
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

