ssh_authorized_keys:
  - github:ssmiller25
write_files:
- enconding: ""
  content: |-
    #!/bin/bash
    write_log () {
        local message="${1}"
        logger -t "run-cmd" "${message}"
        echo "${message}"
    }
    write_log "Getting the service using eth0..."
    ETH0=$(connmanctl services | awk '{ print $3 }' | while read -r s1; do connmanctl services $s1 | grep -q "eth0" && echo "$s1"; done)
    write_log "eth0 is bound to: ${ETH0}"
    write_log "Setting up manual net config..."
    connmanctl config $ETH0 --ipv4 manual {{.ip}} {{.netmask}} {{.gateway}} --nameservers {{.nameservers}}
    connmanctl config $ETH0 --domains r15cookie.lan
    connmanctl config $ETH0 --ipv6 off
    write_log "Restarting connman..."
    service connman restart
    write_log "$(connmanctl services $ETH0)"
    write_log "Network setup done."
  owner: root:root
  path: /etc/run-cmd.sh
  permissions: '0755'
run_cmd:
- "/etc/run-cmd.sh"
hostname: {{.hostname}}
k3os:
  modules:
  - kvm
  dns_nameservers:
  - 172.18.110.5
  - 8.8.8.8
  ntp_servers:
  - 0.us.pool.ntp.org
  - 1.us.pool.ntp.org
  k3s_args:
  - agent
  environment:
    INSTALL_K3S_SKIP_DOWNLOAD: true
