apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pihole

configMapGenerator:
  - name: pihole-custom-dnsmasq
    files:
    - configmap/02-custom.conf
    - configmap/addn-hosts

resources: 
- ns.yaml
# TODO - move secret to SealedSecret (this is a generic password for now)
- secret.yaml
- deployment.yaml
- service.yaml
- service-external.yaml
