---
apiVersion: v1
kind: Service
metadata:
  name: pihole-external-udp
  namespace: pihole
spec:
  ports:
  - port: 53
    protocol: UDP
    targetPort: dns-udp
  selector:
    app: pihole
    release: pihole
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-external-tcp
  namespace: pihole
spec:
  ports:
  - port: 53
    protocol: TCP
    targetPort: dns
  selector:
    app: pihole
    release: pihole
  type: LoadBalancer