apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grocy
  name: grocy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grocy
  template:
    metadata:
      labels:
        app: grocy
    spec:
      volumes:
        - name: grocy-storage
          persistentVolumeClaim:
            claimName: grocy-storage
      containers:
        - image: linuxserver/grocy:version-v3.0.1
          name: grocy
          env:
            - name: PUID
              value: "1004"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Chicago"
          volumeMounts:
            - mountPath: "/config"
              name: grocy-storage
---
apiVersion: v1
kind: Service
metadata:
  name: grocy
spec:
  selector:
    app: grocy
  ports:
    - protocol: TCP
      port: 80
      name: http
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grocy-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi